### ISSUE TITLE
Possible requires domain name

### ISSUE THREAD

**Issue by TayBill** [jsumners/node-activedirectory#10]
Note that (after MUCH experimentation), we found that we needed to 
1. add the domain name in front of the username, with separated double slashes  
2. remove the domain name after the user name. (code removed)

See snip below.

const AD = require('activedirectory2').promiseWrapper;
const config = { url: 'ldap://dc.domain.com',
               baseDN: 'dc=domain,dc=com',
               username: 'MYDOMAIN\\username', 
               password: 'password' }
const ad = new AD(config);

**Comment by jsumners** [comment]
FYI: in the main configuration, it is best to use a full DN for the username. The `authenticate` method _should_ look up a DN for plain usernames.
