### ISSUE TITLE
IsUserMemberOf & getGroupMembershipsForUser

### ISSUE THREAD

**Issue by wbautistaEXPEDIA** [jsumners/node-activedirectory#11]
The two apis in the title do not work as expected. When I check my if my user is in a group that I am a member of, it returns false. When I get the memberships for my user, only five groups are returned, none of which is the group I am interested in and know I am a member. However, when I use the getUsersForGroup api for the group I am interested in, all expected users are returned, including my user.

**Comment by jsumners** [comment]
I am unable to replicate these problems in my environment. Have you enabled trace logging to look for any errors?

```
ad.isUserMemberOf('jsumners', 'foo', (err, result) => {
  console.log(result) // logs 'true'
})

ad.getGroupMembershipForUser('jsumners', (err, groups) => {
  console.log(groups.length) // logs '54'
})
```

**Comment by wbautistaEXPEDIA** [comment]
Ha, definitely user error. My apologies. I had a few stored requests for my service, and I was using one with different credentials than expected. I appreciate the quick turnaround. Thanks.
