### ISSUE TITLE
Question: FindUser() by employeeID

### ISSUE THREAD

**Issue by rjapayne** [jsumners/node-activedirectory#14]
Is there a way to use the FindUser() function to find a user by the emplyeeID attribute instead of the sAMAccountName?
I assume I have to use opts filter or something but I haven't been able to work it out.

**Comment by jsumners** [comment]
The docs say you can use a custom filter https://github.com/jsumners/node-activedirectory#findUser

But I wouldn't be surprised if that is unimplemented. I would recommend using the regular `find` method -- https://github.com/jsumners/node-activedirectory#find

**Comment by rjapayne** [comment]
Success! Thanks so much!
