### ISSUE TITLE
entryParser

### ISSUE THREAD

**Issue by drichardson-uk** [jsumners/node-activedirectory#21]
I'm trying to create a custom entry parser by adding an entryParser attribute to my config.  However, the function I've specified never gets called.  Is that a known issue?

Config I'm using:

`{
        url: 'ldap://****.com',
        baseDN: 'dc=****,dc=com',
        attributes: {
            user: ['sAMAccountName', 'employeeID', 'givenName', 'sn', 'mail', 'mobile', 'title', 'department', 'userAccountControl', 'thumbnailPhoto']
        },
        username: '****',
        password: '****',
        entryParser: customEntryParser
    }`

And this is my function:

`function customEntryParser(entry, raw, callback){
    if (raw.hasOwnProperty("thumbnailPhoto")){
        entry.thumbnailPhoto = raw.thumbnailPhoto;
    }
    callback(entry);
};`

**Comment by jsumners** [comment]
It is not a known issue. Would you like to submit a PR to fix it?

**Comment by drichardson-uk** [comment]
I was wondering if I was doing something wrong

**Comment by jsumners** [comment]
Not according to the documentation. But that's a feature I haven't ever had a need to use. I suspect there needs to be an invocation of the user supplied parser around https://github.com/jsumners/node-activedirectory/blob/00ddcfb86b2e73d36c3a4b432d35fed331f63e8f/lib/components/search.js#L212

**Comment by ofaltins** [comment]
@drichardson-uk I had the same problem, it seems like custom entryParsers are not recognised. I wrote a fix for it here: https://github.com/adsign/node-activedirectory/pull/1/files

You can test if it works for you by changing your package.json from:

`"activedirectory2": "^1.2.5"`

to

`"activedirectory2": "adsign/node-activedirectory"`

**Comment by jsumners** [comment]
@ofaltins why don't you just submit a PR to this repository?

**Comment by ofaltins** [comment]
@jsumners sure thing! i'll do a little more testing and clean it up a little. Thanks for a great repo @jsumners

**Comment by jsumners** [comment]
Close in #28.
