### ISSUE TITLE
Add maintainer?

### ISSUE THREAD

**Issue by jsumners** [jsumners/node-activedirectory#22]
@jurjendijkstra would you like to be a maintainer on this project?

(I wish @github had a way to private message people.)

**Comment by jurjendijkstra** [comment]
I am honoured! But I am not up to the task, I am just a beginner in JavaScript. I have tried to study your code when I needed that paged thing, but it goes over my head. 
So it's in your best interest when I decline. 
But thanks anyway, your invitation has brightened my day :-)

**Comment by jsumners** [comment]
Okay, thank you for considering it.

BTW, if you have questions, don't hesitate to ask.
