### ISSUE TITLE
Error with Webpack

### ISSUE THREAD

**Issue by jimsleon** [jsumners/node-activedirectory#23]
in adpromise.js, it is requiring 'activedirectory.js' as following, which will cause issue when using Webpack to bundle the code. why not just using 'require('./activedirectory');'? are there some special purpose of this code?

const AD = require(path.join(__dirname, 'activedirectory'))

**Comment by jsumners** [comment]
It's old code. `require('./activedirectory')` would be perfectly fine if you want to submit a PR.

**Comment by Jpec07** [comment]
#35

**Comment by jsumners** [comment]
Fix published as 1.2.7
