### ISSUE TITLE
Promise execution order

### ISSUE THREAD

**Issue by AMMullan** [jsumners/node-activedirectory#27]
I'm still learning Node and this package is really useful but I'm having an issue with promise execution order, quite likely because I'm a complete noob to node ;)

So I've got this:
```
ad.findGroups(groupName)
.then((groups) => {
    groups.forEach(function(group) {
        ad.getUsersForGroup(group.dn)
        .then((users) => {
            users.forEach(function(user) {
                group_members.push([group.cn, user.sAMAccountName])
            })
        })
    })

})
.then(() => {
    console.log('this executes before the first then()...')
})
.catch((exception) => {
    console.log(exception)
})
```

Ideally I'd like to have my addUsersToDB() call in the second then() call but it executes first, which I thought wasn't meant to be the case with promise chaining. Basically I just want to have all my users in the groupName to be put in a variable and then I can call my SQL bits afterward. Anyone got any tips? :)

A

**Comment by jsumners** [comment]
If you're going to be working with promises, I recommend you use Node 8 (LTS):

```js
async function buildGroupMembersArray (groupName) {
  const groups = await ad.findGroups(groupName)
  const result = []
  groups.forEach(async (group) => {
    const users = await ad.getUsersForGroup(group.dn)
    users.forEach((user) => result.push([group.cn, user.sAMAccountName])
  })
  return result
}

buildGroupMembersArray
  .then(addUsersToDB)
  .catch(console.error)
```

I hope that gets you going in the right direction. In the future, please keep issues on topic (i.e. specifically about problems with this module) and direct general Javascript/Node.js questions to https://stackoverflow.com/ .
