### ISSUE TITLE
Equivalent from Powershell commands

### ISSUE THREAD

**Issue by Aymkdn** [jsumners/node-activedirectory#29]
Hi,

I'm currently using PowerShell commands to retrieve the members of a distribution list (that is also a security group), and to retrieve all the direct reports for a director. I'd like to use Node/JS to do it.

I'm not from I/T and I don't have special privilegies or knowledge with AD/LDAP.

We have several LDAP servers (I found them using the command `nslookup -type=srv _ldap._tcp.DOMAIN.COM`). I'm not sure there are differences between them (I tried a couple of them during my tests).

With your module I'm able to search for `cn=*Exchange*` which returns some results, but none of the other things I tried worked (for example `findUser`).
```javascript
var ActiveDirectory = require('activedirectory2').promiseWrapper;
var config = { url: 'ldap://ldap_server.domain.com',
              baseDN: 'dc=domain,dc=com',
              username: 'my_username@domain.com',
              password: 'MyP@ssword' }
var ad = new ActiveDirectory(config);
var user = 'UserName_To_Search';
ad.findUser(user, function(err, results) {
  if (err) {
    console.log('ERROR: ' +JSON.stringify(err));
    return;
  }

  if (!results) console.log('User: ' + user + ' not found.');
  else console.log(JSON.stringify(results));
})
// -> User: UserName_To_Search not found.
```

We have several domain (example: WEST, EAST, NORTH and SOUTH), and users can only be found in their own domain. 
For example, I'm in the SOUTH domain, so with Powershell if I type : `Get-ADUser -Identity $user` it will search in SOUTH.DOMAIN.COM. If the user is in the same domain as me, it works and returns info, if not it says the user cannot be found.
In that second case, I have to specify the server : `Get-ADUser -Identity $user -Server WEST.DOMAIN.COM` (if the user is in WEST domain).

The identity for a user in SOUTH looks like : `CN=John_Doe,OU=Users,OU=CityName,DC=South,DC=domain,DC=com`

During my tests with `findUser` I tried a user in SOUTH domain.

So.... can I use your module to query the active diretory in order to get all users from a group and all direct reports for a manager, based on the configuration we have ?

Thanks

**Comment by jsumners** [comment]
The various servers are typically replicas, e.g. for load balancing. But they _might_ have different datasets; I have no way of knowing your setup.

You should specify `scope: 'sub'` in your options. The default, as is the normal default in the LDAP protocol, is to search only within the specified `baseDN`. According to your information, the user is in `OU=Users,OU=CityName,DC=South,DC=domain,DC=com` which is a subtree of `DC=domain,DC=com` (your specified `baseDN`).

**Comment by Aymkdn** [comment]
Thanks.

I tried the `{ scope:'sub' }` and I tried to query all servers one by one, but no change here :-(

I also tried to change the `baseDN` to `baseDN: 'OU=Users,OU=CityName,DC=south,DC=domain,DC=com'` but I receive an error: `ERROR: {"lde_message":"0000202B: RefErr: DSID-03100742, data 0, 1 access points\n\tref 1: 'south.domain.com'\n\u0000","lde_dn":null}`

Any other idea ?

**Comment by jsumners** [comment]
That's an error message directly from the LDAP server. You'll have to investigate what it means.

**Comment by Aymkdn** [comment]
OK... Thanks anyway :)
