### ISSUE TITLE
can we use activedirectory package to manipulate ad user data?

### ISSUE THREAD

**Issue by virajbahulkar** [jsumners/node-activedirectory#34]

**Comment by jsumners** [comment]
Sorry, no. This library does not include any way to write to AD. The `adldap` module, however, does.

**Comment by jsumners** [comment]
This project is a fork of a prior project. Most of the documentation carries over from that fork. If it is incorrect, please submit a PR to fix it. I do not know of any code in the project that allows for writing to an Active Directory database.

**Comment by jurjendijkstra** [comment]
The documentation does not look incorrect to me: you can manipulate the search results with custom entry parsing.  It is a way to parse and change the results that are in the response of the search. Not that I have tried the feature, did not need it. But how I interpret the text, manipulating the search results has nothing to do with saving data in AD.

**Comment by jsumners** [comment]
👍

**Comment by jsumners** [comment]
@virajbahulkar has your question been sufficiently answered? Can we close this issue?
