### ISSUE TITLE
canonicalName not being returned in search results of user objects

### ISSUE THREAD

**Issue by tfrancois** [jsumners/node-activedirectory#38]
Does anyone know how to return the canonicalName attribute for AD users? I realized that the canonicalName attribute is a computed value and is not really saved in Active Directory,  but since I am able to retrieve the dn property, maybe it can be constructed from that property? Anyone have an idea how to tackle this?  Please help.  Thanks.

**Comment by jsumners** [comment]
Sorry, I do not know the answer to this. I no longer have an ActiveDirectory instance to test against.

**Comment by tfrancois** [comment]
@jsumners I can help with that if you'd be gracious enough to take a look.  Where can I send the LDAP connection info please sir?

**Comment by tfrancois** [comment]
Following up on this, I came across a library that returns constructed attributes without issue! And it does not list ldapjs as a dependency, but makes use of it's same dependencies.  Nevertheless, all attributes are returned that activeDirectory2 has trouble returning like `canonicalName` and others such as `msDS-User-Account-Control-Computed`.  Can ad2 be updated to use the same methodologies applied therein?  My source is too heavily reliant on this ad2 to make the switch to this other library and I'm hoping it won't be too hard to leverage the same technique(s) used to produce the desired results.  Without it, ad2 is slightly incomplete.

**Comment by jsumners** [comment]
Given https://github.com/ldapjs/node-ldapjs/issues/567 I conclude this is not an issue with `activedirectory2`. Therefore, I am closing this issue.
