### ISSUE TITLE
authenticate() check the wrong field

### ISSUE THREAD

**Issue by LoickMunoz** [jsumners/node-activedirectory#40]
Hi,

When i use authenticate(username, password), it checks the cn.
Is there a way to use authenticate with the sAMAccountName ?

**Comment by jurjendijkstra** [comment]
I think the way is:
first    ad.findUser(userPrincipalName)
then   ad.authenticate(aduser.distinguishedName, password)

**Comment by jurjendijkstra** [comment]
Sorry, that answer was not very good.   ad.findUser(sAMAccountName)  should also work.
