### ISSUE TITLE
After update node-activedirectory2 from 1.2.8 to 1.2.9 function getGroupMembershipForUser stoped working if user is located in OU with non-US-ASCII characters.

### ISSUE THREAD

**Issue by Casm82** [jsumners/node-activedirectory#49]
Hello!

Sorry for my English.

After update node-activedirectory2 from 1.2.8 to 1.2.9 function getGroupMembershipForUser stoped working if user is located in OU with non-US-ASCII characters.

I created user user01 and two OU:
-  **OU=OU-ASCII-ABCD,DC=domain,DC=org** - OU only US-ASCII characters
-  **OU=OU-UTF8-АБВГ,DC=domain,DC=org**  - OU with UTF-8 characters, АБВГ - U+0410 U+0411 U+0412 U+0413

I added user01 in to two groups:

-  **CN=Support,CN=Users,DC=domain,DC=org** - group only US-ASCII characters
-   **CN=пользователи,OU=Departments,DC=domain,DC=org** - group with UTF-8 characters

I modified **node_modules/activedirectory2/lib/activedirectory.js** to enable debug output
 ```
//let log = require('abstract-logging')
 let bunyan = require('bunyan');
 let log = bunyan.createLogger({name: "ADDebug", level: "trace"});
```
I started this example:
 ```
 const ActiveDirectory = require("activedirectory2");
  const config = {
    url: 'ldap://192.168.1.1',
    baseDN: 'DC=domain,DC=org',
    username: 'nodejs@domain.org',
    password: 'password'
  }
  const ad = new ActiveDirectory(config);
  const sAMAccountName='user01';
  ad.getGroupMembershipForUser(sAMAccountName, function(err, groups) {
    console.log(groups);
  });
```

If user01 is located in "**OU=OU-UTF8-АБВГ,DC=domain,DC=org**" search node-activedirectory2 v1.2.9 ended with this:
  ```
...
  {"name":"ADDebug","hostname":"client02","pid":12858,"level":10,"msg":"getGroupMembershipForDN({},CN=user01,OU=OU-UTF8-АБВГ,DC=domain,DC=org)","time":"2019-10-03T10:27:52.891Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12858,"level":10,"msg":"Adding PagedResultControl to search (DC=domain,DC=org) with filter \"(member=CN=user01,OU=OU-UTF8-\\\\410\\\\411\\\\412\\\\413,DC=domain,DC=org)\" for undefined","time":"2019-10-03T10:27:52.892Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12858,"level":10,"msg":"Querying active directory (DC=domain,DC=org) with filter \"(member=CN=user01,OU=OU-UTF8-\\\\410\\\\411\\\\412\\\\413,DC=domain,DC=org)\" for [\"dn\",\"cn\",\"description\",\"distinguishedName\",\"objectCategory\",\"groupType\"]","time":"2019-10-03T10:27:52.893Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12858,"level":10,"msg":"Active directory search (DC=domain,DC=org) for \"(member=CN=user01,OU=OU-UTF8-\\5c410\\5c411\\5c412\\5c413,DC=domain,DC=org)\" returned NaN entries.","time":"2019-10-03T10:27:52.899Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12858,"level":10,"msg":"Group \"CN=user01,OU=OU-UTF8-АБВГ,DC=domain,DC=org\" has 0 group(s). Groups: []","time":"2019-10-03T10:27:52.899Z","v":0}

```
  full log: https://gist.github.com/Casm82/ab39868e63099178d348de096ff64dad

If user01 is located in "**CN=user01,OU=OU-ASCII-ABCD,DC=domain,DC=org**" search node-activedirectory2 v1.2.9 ended with this:
  ```
...
  {"name":"ADDebug","hostname":"client02","pid":12843,"level":10,"msg":"Active directory search (DC=domain,DC=org) for \"(member=CN=Support,CN=Users,DC=domain,DC=org)\" returned NaN entries.","time":"2019-10-03T10:27:28.658Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12843,"level":10,"msg":"Group \"CN=Support,CN=Users,DC=domain,DC=org\" has 2 group(s). Groups: [\"CN=Support,CN=Users,DC=domain,DC=org\",\"CN=пользователи,OU=Departments,DC=domain,DC=org\"]","time":"2019-10-03T10:27:28.658Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12843,"level":10,"msg":"Active directory search (DC=domain,DC=org) for \"(member=CN=\\5c43F\\5c43E\\5c43B\\5c44C\\5c437\\5c43E\\5c432\\5c430\\5c442\\5c435\\5c43B\\5c438,OU=Departments,DC=domain,DC=org)\" returned NaN entries.","time":"2019-10-03T10:27:28.659Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12843,"level":10,"msg":"Group \"CN=пользователи,OU=Departments,DC=domain,DC=org\" has 2 group(s). Groups: [\"CN=Support,CN=Users,DC=domain,DC=org\",\"CN=пользователи,OU=Departments,DC=domain,DC=org\"]","time":"2019-10-03T10:27:28.659Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12843,"level":10,"msg":"Group \"CN=user01,OU=OU-ASCII-ABCD,DC=domain,DC=org\" has 2 group(s). Groups: [\"CN=Support,CN=Users,DC=domain,DC=org\",\"CN=пользователи,OU=Departments,DC=domain,DC=org\"]","time":"2019-10-03T10:27:28.659Z","v":0}

```
  full log: https://gist.github.com/Casm82/b357a2bf1ba03225f57db90229a4f1ea

If i use **node-activedirectory2 v1.2.8**, then the search is successful, regardless of the user's location:
  ```
...
  {"name":"ADDebug","hostname":"client02","pid":12945,"level":10,"msg":"Active directory search (DC=domain,DC=org) for \"(member=CN=Support,CN=Users,DC=domain,DC=org)\" returned NaN entries.","time":"2019-10-03T10:35:15.516Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12945,"level":10,"msg":"Group \"CN=Support,CN=Users,DC=domain,DC=org\" has 2 group(s). Groups: [\"CN=Support,CN=Users,DC=domain,DC=org\",\"CN=пользователи,OU=Departments,DC=domain,DC=org\"]","time":"2019-10-03T10:35:15.516Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12945,"level":10,"msg":"Active directory search (DC=domain,DC=org) for \"(member=CN=пользователи,OU=Departments,DC=domain,DC=org)\" returned NaN entries.","time":"2019-10-03T10:35:15.517Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12945,"level":10,"msg":"Group \"CN=пользователи,OU=Departments,DC=domain,DC=org\" has 2 group(s). Groups: [\"CN=Support,CN=Users,DC=domain,DC=org\",\"CN=пользователи,OU=Departments,DC=domain,DC=org\"]","time":"2019-10-03T10:35:15.517Z","v":0}
  {"name":"ADDebug","hostname":"client02","pid":12945,"level":10,"msg":"Group \"CN=user01,OU=OU-UTF8-АБВГ,DC=domain,DC=org\" has 2 group(s). Groups: [\"CN=Support,CN=Users,DC=domain,DC=org\",\"CN=пользователи,OU=Departments,DC=domain,DC=org\"]","time":"2019-10-03T10:35:15.517Z","v":0}

```
  full log: https://gist.github.com/Casm82/8d3b6570bec58ae35c1cbe57b8b8ebe8

**Comment by jsumners** [comment]
Regarding the logger, just pass in your logger instance as an option when creating the client.

Regarding the issue, unless @jurjendijkstra has time and a willingness to look at this, then it would be best if you are able to submit a PR yourself. I cannot give an estimate on when I would be able to (it'd be in the weeks or months time scale).

**Comment by jurjendijkstra** [comment]
Omg I am so sorry! The prime suspect is this statement that I submitted for release 1.2.9 :

`
            if (char.charCodeAt(0) > 122) {
              char = '\\\\' + char.charCodeAt(0).toString(16).toUpperCase()
            }
`

in lib/components/utilities.js

https://github.com/jsumners/node-activedirectory/blob/2666ae3a876e5453074fd50a6d659f4bdfd15378/lib/components/utilities.js#L324

What did I do wrong? What should it be, I have no idea because I don't know how I can set up an experiment with cyrillic. @Casm82  could you maybe experiment a bit with that statement to see what works for you?

What I was trying to achieve was this:

"You can escape any characters in distinguished names, including foreign and other non-keyboard characters. Use the backslash escape character "\" and the two character ASCII hexadecimal representation of the character. For example:
|Character in Distinguished Name | Hex Representation|
|-- | --|
|á | \E1|
|é | \E9|
|í | \ED|
|ó | \F3|
|ú | \FA|
|ñ | \F1|
"

**Comment by Casm82** [comment]
I looked at data exchange between AdExplorer (from Sysinternals) and Active Directory using Wireshark

if I make search **(distinguishedName=OU=OU-UTF8-АБВГ,DC=domain,DC=org)**
the string АБВГ is presenting as **d0 90 d0 91 d0 92 d0 93** in network packet
Search returned OU in the result.

if I make search **(distinguishedName=OU=OU-UTF8-\410\411\412\413,DC=domain,DC=org)** 
the string is presenting as A0A1A2A3 in network packet
no OU founded 

Microsofts the documentation says:
"Use the backslash escape character "\" and the two character ASCII hexadecimal representation of the character"
So I tried utf-8 representation symbols:
 А - 0xDO, 0x90 (UTF-16 0x0410)
 Б - 0xDO, 0x91 (UTF-16 0x0411)
 В - 0xDO, 0x92 (UTF-16 0x0413)
 Г - 0xDO, 0x93 (UTF-16 0x0413)
I makeed search **(distinguishedName=OU=OU-UTF8-\d0\90\d0\91\d0\92\d0\93,DC=domain,DC=org)** 
The string presentation in network packet is the same as АБВГ.
Search returned OU in the result.

So, instead backslash escape and one UTF-16 hex representation of character, necessary use backslash escape and two UTF-8 representation of the character. 

I modified function parseDistinguishedName in the component/utilites.js so that return two character ASCII hexadecimal representation of the character for my query.
```
...
 case 'Б':
    char = '\\d0\\91'
    break 
...
```
but it's not working - in network packet \d0\91 represented as 64 30 39 31
May be ldapjs also does character escaping.

This Powershell command creates OU test-Б
`
New-ADOrganizationalUnit -Name "test-$(0x411 -as [char])" -ProtectedFromAccidentalDeletion $false
`

**Comment by jurjendijkstra** [comment]
@Casm82  Alexander have you found any improvement yet? 

I just received a bug report that someone with "d’Olieslagers" in his name does not come through, because of that thingy between the d and the O. I don't think it is a double-byte character so it is different than your problem, although it is clearly affected by the same source code lines (324-326).

Perhaps it is best if lines 324 - 326 are simply removed from utilities.js because they seem to do more harm than good.

**Comment by Casm82** [comment]
@jurjendijkstra I commented out a 325 line in utilites.js, this solved my problem
