### ISSUE TITLE
Can the snazzy dependency be removed from the package?

### ISSUE THREAD

**Issue by tfrancois** [jsumners/node-activedirectory#50]
Hi looking into why the activedirectory2 package lists this as a dependency?  If it is not needed or is optional, can it be removed or changed to a dev dependency?  I am trying to package my code for distribution and keep it as lean as possible and snazzy and all its dependencies are adding bloat.  

I want to be able to run `npm update` without worrying to have to remove the dependency manual each time.

**Comment by jsumners** [comment]
Clearly it is a dev dependency mistakenly saved as a prod dependency.

**Comment by tfrancois** [comment]
Excellent news.  Can it be removed and updated on npm accordingly please.

**Comment by jsumners** [comment]
Submit a PR and I’ll get to it when I can.

**Comment by tfrancois** [comment]
Hi @jsumners but I am not experienced on how to do a PR and I took a look to see if I can do it but the last thing I want to do is screw it up.  If you send instructions I'll gladly do it but I googled around and found a few how-tos and still couldn't figure it out.  Please update/fix the issue when you can.  Thanks.

**Comment by jsumners** [comment]
https://jrfom.com/posts/2017/03/08/a-primer-on-contributing-to-projects-with-git/

This library is open source software. It is provided free of charge on an as-is basis. I do not have time to jump at ultimatums regarding it. If you cannot contribute the fix you wish to see implemented, then you will have to wait until I get time, and the will, to deal with it.
