### ISSUE TITLE
getUsersForGroup crashes if group is member of itself

### ISSUE THREAD

**Issue by jurjendijkstra** [jsumners/node-activedirectory#58]
We just had an issue where nodejs crashed with out of stack space. I analyzed and found that getUsersForGroup was called for a group, which had a member that was that group itself. So getUsersForGroup recursed forever until out of stack space.

I wonder if it is possible for getUsersForGroup to discover that a subgroup was already processed so it knows that it can end the recursion.

**Comment by jsumners** [comment]
I'd definitely welcome a PR for it.

P.S.: the invitation to be a direct maintainer of the module is still open to you @jurjendijkstra.

**Comment by jurjendijkstra** [comment]
It appears that the issue is different:  there are two groups with exactly the same name (but with different DN of course) and the first group is member of the second group. The second group is not a member of the first group, the recursion is not what I thought it was. So now I doubt if this issue is still valid. But there was still a crash with out of stack space.... may need testing to reproduce the issue and see what it is exactly.

I am still honored that you think I could be a maintainer. But I am afraid I would mess up, I am not that smart with JavaScript :-(

**Comment by jsumners** [comment]
Glad you’re making progress.
