### ISSUE TITLE
Suggestion: Is there any way to have a 'next' build/version that supports ldapJS@next?

### ISSUE THREAD

**Issue by tfrancois** [jsumners/node-activedirectory#59]
@jsumners, sir if i can be so bold...is there any way to have a build/version of this library that supports the ldapjs@next (currently ldapjs v2.0.0-pre.5) library as a dependency.  Why, you may ask? My current project uses the current build of activedirectory2 (v1.3.0) with the only change I've made is to the required dependencies: changing my package.json to utilize the latest builds of (async v3.1.0, ldapjs@next, abstract-logging v2.0.0, merge-options v2.0.0) and with extensive testing (and I mean extensive) I have found no incompatibilities whatsoever!  The MAJOR benefit to this exercise is the vast difference in the size of the overall package.  My project with these overridden newer dependencies is slimmer by a magnitude of almost 3:1! I think in huge part to the difference in requirements of async@3.1 vs. async@2.5.0 and ldapjs@next vs. ldapjs@1.0.1, both of which the latter is the current requirement of activedirectory2.  Again, I've changed ALL the dependencies in this library to the latest available builds (as the minimum versions) and seen a huge change in the overall size of the project.  

At a minimum, what I'm asking is why not update the dependencies to use higher minimum versions so as to take advantage of the smaller footprint and newer codebases?  Thanks.

**Comment by jsumners** [comment]
It is not as simple as you suspect. Bumping the dependency immediate results in the test suite failing.

https://github.com/jsumners/node-activedirectory/commit/ea437f9dbcca0eb210795ea709d302e5e24a6444

https://circleci.com/gh/jsumners/node-activedirectory/97?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jsumners** [comment]
https://github.com/jsumners/node-activedirectory/pull/62

**Comment by tfrancois** [comment]
You sir...are a ROCK STAR.  How fortunate are we that you are still supporting this community and your excellent work.  If you only knew how important your contribution is.  Thank you.  Hope you have a wonderful 2020.
