### ISSUE TITLE
Combined searches ?

### ISSUE THREAD

**Issue by burton666** [jsumners/node-activedirectory#63]
Firstly I must admit that I am completly new to active directory and this is my first attempt trying to collect data using ad.

I managed to get a simple example working:

```
const config = {
  url: "ldap://<url>",
  baseDN: "OU=Users,OU=Default,DC=<dc>,DC=intra,DC=local",
  username: "<user>",
  password: "<pass>"
};

let sAMAccountName = "test";

let ad = new ActiveDirectory(config);
ad.findUser(sAMAccountName, function(err, user) {
  console.log(JSON.stringify(user.displayName));
});;
```
But then I need to use the variable `user.displayName` in another search using another baseDN:
`baseDN: 'OU=Laptops,OU=LmComputers,DC=<dc>,DC=intra,DC=local'`

to be able to get the returned users computer-info. What is the preferred way to do this?

**Comment by jsumners** [comment]
What you are asking for is help with application design. This issue tracker is for problems with the library itself. I am sorry, but I don't really have time to even maintain this library so I _really_ don't have time to aid people with application design.

I recommend posing such questions to https://softwareengineering.stackexchange.com/

**Comment by jurjendijkstra** [comment]
if I may chime in: it seems to me that 'OU=Laptops,OU=LmComputers,DC=<dc>,DC=intra,DC=local' is not a baseDN, but 'DC=<dc>,DC=intra,DC=local' is.  Or maybe 'DC=intra,DC=local'.

So if you put that baseDN in the config and use that to create ad = new ActiveDirectory(config), then you can use that ad instance many times for different queries, as long as everything you search for is indeed inside that baseDN.

**Comment by jurjendijkstra** [comment]
Oh but findUser finds a user, i.e. an object of type user. I doubt if it will find a laptop.
