### ISSUE TITLE
cannot resolve dependencies errors when building webpack

### ISSUE THREAD

**Issue by donnrriz** [jsumners/node-activedirectory#7]
I have installed activedirectory2 
Followed up a basic example:
var ActiveDirectory = require('activedirectory2');
var config = { url: '...',
               baseDN: '....',
               username: '...',
               password: '....' }
var ad = new ActiveDirectory(config);

When I build my project using webpack2 I get the following errors:

Can't resolve 'net' in 'C:\...\node_modules\ldapjs\lib'
Can't resolve 'tls' in 'C:\...\node_modules\ldapjs\lib'
Can't resolve 'net' in 'C:\...\node_modules\ldapjs\lib\client'
Can't resolve 'tls' in 'C:\...\node_modules\ldapjs\lib\client'
Can't resolve 'fs' in 'C:\...\node_modules\bunyan\lib'
Can't resolve 'fs' in 'C:\....\node_modules\mv
Can't resolve 'fs' in 'C:\...\node_modules\ncp\lib
Can't resolve 'fs' in 'C:\...\node_modules\mv\node_modules\rimraf
Can't resolve 'fs' in 'C:\...\node_modules\mkdirp
Can't resolve 'fs' in 'C:\...\node_modules\mv\node_modules\glob

If anyone has any ideas about resolving this I be very graeful for any comments

**Comment by jsumners** [comment]
Sorry, I am unable to support webpack. In fact, I don't think it would even be possible.

**Comment by donnrriz** [comment]
For anyone else getting these errors.
Add    
node: {
        console: false,
        fs: 'empty',
        net: 'empty',
        tls: 'empty'
    },

Into you webpack.config.  The modules 'fs' , 'tls' are node modules and should be ignored in the broswer - the above config addition will allow that.   Thanks for the library jsumners !

**Comment by donnrriz** [comment]
Oh yes also see https://github.com/trentm/node-bunyan/issues/392  to deal with other issues
