### ISSUE TITLE
Exception caused by ldapjs@2.1.0

### ISSUE THREAD

**Issue by mugi-luffy** [jsumners/node-activedirectory#78]
when I run this script: 

```
var ActiveDirectory = require('activedirectory2');

let adUrl = "ldap://myurl"
let userName = "myuser"
let password = "mypw"

var ad = new ActiveDirectory({ url: adUrl })
ad.authenticate(userName, password, function (err, auth) {if (!error) console.log("valid user")}
```

I get the following exception:

> /.../node_modules/activedirectory2/node_modules/ldapjs/lib/url.js:15
>       throw new TypeError(urlStr + ' is an invalid LDAP url (scope)')
>       ^
> 
> TypeError: ldap://myurl is an invalid LDAP url (scope)
>     at Object.parse (/.../node_modules/activedirectory2/node_modules/ldapjs/lib/url.js:15:13)
>     at new Client (/.../node_modules/activedirectory2/node_modules/ldapjs/lib/client/client.js:114:33)
>     at Object.createClient (/.../node_modules/activedirectory2/node_modules/ldapjs/lib/client/index.js:17:12)
>     at Object.createClient (/.../node_modules/activedirectory2/lib/components/utilities.js:25:15)
>     at ActiveDirectory.authenticate (/.../node_modules/activedirectory2/lib/activedirectory.js:933:24)

Changing the version of ldapjs to 1.0.2 in the package.json fixes the problem!

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by mugi-luffy** [comment]
the error does not occur when using the most recent node lts v12.18.3
Was using an older version of node which seems to be not compatible with ldapjs@2.1.0
