### ISSUE TITLE
Is there a way to perform case-insensitive search?

### ISSUE THREAD

**Issue by shelagh-lewins-ucl** [jsumners/node-activedirectory#80]
Hi, this is a great package, thank you.

However it seems that findUsers performs a case sensitive search.

Is there any way to make the search case insensitive?

**Comment by jsumners** [comment]
I don't recall anything specific in the code to issue case sensitive searches. Can you show me where such is being set?

**Comment by shelagh-lewins-ucl** [comment]
Hmm, now I check again, I am not seeing the problem. Code is weird. My apologies for the false issue.
