### ISSUE TITLE
`getUsersForGroup` returns just one user when there is a group with nested groups

### ISSUE THREAD

**Issue by SelfDevTV** [jsumners/node-activedirectory#84]
Hiho,

Today I stumbled over a bug:

I have a group with 2 sub groups. Both have combined ~a bit over 1000 Users~ 640 Users:

![image](https://user-images.githubusercontent.com/48333000/90233813-fcce8700-de1e-11ea-9c15-ddc810cab37e.png)

The result I get ist just one random user from one of those sub groups. It's always this user. 

When I turn on logging I can see this: 

![image](https://user-images.githubusercontent.com/48333000/90231322-4b7a2200-de1b-11ea-9744-98d34d8a6e02.png)

The last line where it says "1 user belong.." this is the user I receive back when I res.send those results. 

If I use a group with 3000+ direct users it will work just fine. 

I tried it with several groups that have subgroups. The result is always the same.

Here is the code:

```
app.post("/api/getGroupMembers", (req, res) => {
  const group = req.body.group;

  ad.getUsersForGroup(group, (err, users) => {
    if (err) {
      console.log("error in getUsers", err);
    }
    res.send(users);
  });
});
```

**EDIT:** it seems to work with "activedirectory" package, the one I use and it isn't working is this: "activedirectory2".
**Edit2:** I have added this group that does not work to my test group with 5 users in it. The result is this, when I query the testgroup:

*I get the 5 users in the group and again this one random user from this big group with sub groups. So 6 in total.*

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jurjendijkstra** [comment]
I am interested to know if this issue may affect me too, so I want to look into it.
Are you willing to send me more logging? I mean in fact the whole log (except the first couple of lines where the authentication happens). The snippet of 3 selected lines, where names are censored, does not give any clue at all. You can send it to me in private message if you want.

**Comment by SelfDevTV** [comment]
Thank you very much @jurjendijkstra 
I will have a deeper look in a couple of days. Im on holiday right now and have no access to the company code right now.

**Comment by SelfDevTV** [comment]
Alrighty @jurjendijkstra 

I have now enabled logging and I will send you detailed informations via pn. Thx in advance!

**Comment by SelfDevTV** [comment]
@jurjendijkstra Any chance to solve this problem? Any ideas where I should start to look for? I'm so close to finish my webapp, just this one nasty bug ist left :D

**Comment by jsumners** [comment]
Please see the notice at the top of this module's README. 

I recommend creating the smallest reproduction case possible and stepping through with the debugger to see where the problem occurs.

**Comment by SelfDevTV** [comment]
This has been solved. Attribute `dn` is required in the `config`. For example:

```
var config = {
    url: "your url",
    //....,
    attributes: {
        user: [
            // attributes you want and plus,
            "dn"
        ],
        group: [
            //attributes you want plus:
            "dn"
        ]
    }
}
```
