### ISSUE TITLE
Unable to npm install

### ISSUE THREAD

**Issue by wailuen** [jsumners/node-activedirectory#93]
Hi all,

Had been having problem installing it.. try cleaning cache and deleted the package.json.lock too. On node v14.17.0

npm WARN deprecated grpc@1.23.3: This library will not receive further updates other than security fixes. We recommend using @grpc/grpc-js instead.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@3.2.1: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/wailuen/Downloads/development/express-adsync/node_modules/ldap-client
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CXX(target) Release/obj.target/LDAPCnx/LDAP.o
npm ERR!   CXX(target) Release/obj.target/LDAPCnx/LDAPCnx.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.1.0
npm ERR! gyp info using node@14.17.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.2 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/wailuen/Downloads/development/express-adsync/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/wailuen/Downloads/development/express-adsync/node_modules/ldap-client/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/wailuen/Downloads/development/express-adsync/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/wailuen/Library/Caches/node-gyp/14.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/wailuen/Library/Caches/node-gyp/14.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/wailuen/Downloads/development/express-adsync/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/wailuen/Library/Caches/node-gyp/14.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/wailuen/Downloads/development/express-adsync/node_modules/ldap-client',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../LDAPCnx.cc:42:38: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!   constructor.Reset(tpl->GetFunction());
npm ERR!                     ~~~~~~~~~~~~~~~~ ^
........

**Comment by jsumners** [comment]
What version of Node.js? What operating system? What version of this library are you trying to install?

**Comment by wailuen** [comment]
Hi,

I am on MacOS big sur (11.4). I did not specify which version and thus assume the latest.

**Comment by jsumners** [comment]
I am unable to replicate this issue. There shouldn't be any need for `node-gyp` to install this module, but regardless, check to make sure you are able to build other `node-gyp` based modules.

![image](https://user-images.githubusercontent.com/321201/123797368-1ac89d00-d8b4-11eb-859b-dce1fea0dcea.png)

**Comment by wailuen** [comment]
I upgraded the node to v14.17.1 and managed to install. Thank you .

# npm i activedirectory2

> dtrace-provider@0.8.8 install /Users/wailuen/Downloads/development/express-adsync/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
-----------------------------------------------------------------
Building dtrace-provider failed with exit code 1, falling back
on stub implementation.

Re-run install with V set in your environment to see the build
output, or NODE_DTRACE_PROVIDER_REQUIRE=hard to force an
installation failure.
-----------------------------------------------------------------
  TOUCH Release/obj.target/ndtp.stamp
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN express-adsync@1.0.0 No repository field.

+ activedirectory2@1.3.0
added 39 packages from 49 contributors and audited 39 packages in 11.012s
found 0 vulnerabilities
