### ISSUE TITLE
EADDRINUSE on RD Gateway

### ISSUE THREAD

**Issue by ChristianHaase** [jsumners/node-activedirectory#94]
We have an RDP Gateway and thin clients that our users use.

I'm experiencing issues, receiving error: 

> Error looking up user in Active Directory: Error: connect EADDRINUSE xx.xx.xx.xx:389 - Local (undefined:undefined)

My application is built using Electron.
Anything I'm missing or can do to resolve this issue?

**Comment by jurjendijkstra** [comment]
Something is probably missing in the `config` object that you are passing to the constructor. Can you compare your config object with the constructor example from the documentation:

`var ActiveDirectory = require('activedirectory2');
var config = { url: 'ldap://dc.domain.com',
               baseDN: 'dc=domain,dc=com',
               username: 'username@domain.com',
               password: 'password' }
var ad = new ActiveDirectory(config);
`

**Comment by ChristianHaase** [comment]
The configuration is the same. I'm applying url, baseDN, username and password.

```
const config = {
  url: 'ldap://xx.xx',
  baseDN: 'dc=xx,dc=xx',
  username: 'xx',
  password: 'xx'
}
const ad = new ActiveDirectory(config);
```

**Comment by jurjendijkstra** [comment]
Yes but I'd say there is something wrong with one of the xx's.


Can one of them be fetsched from a configuration database table in a way that one of the attributes is null or undefined?

Is username formatted just like 'christianhaaase' or properly qualified with a domain , like 'christianhaaase@yourdomain.com'

EADDRINUSE is an error that usually means you are trying to start a socket that listens on 389. That should not be happening as you connect to a remote server.

'ldap' protocol without the 's' (in 'ldaps') may be forbidden by the server, but that would probably not explain the EADDRINUSE  error.

Is yours a completely new software which has never worked yet, or did it work first and then began to fail. If so what changed, perhaps a new version or configuration in the server? I have experienced that the system admin installed a new AD version and moved DN's around in the AD without informing me, so things stopped working for me.

I can go on asking questions and all you post is an error message.  It works faster if you tell something.

**Comment by ChristianHaase** [comment]
I apologize for my short descriptions, but I'm not very familiar with Active Directory lookups :)

However, these questions are exactly what I need since I now know what to do and what to ask my AD administrator.

I'm closing this issue as you confirmed this is not an issue with the library, but rather and issue with my configuration or something similar, starting a socket on 389.

Thank you for your help.

**Comment by jurjendijkstra** [comment]
Just wondering, is that activedirectory2 code actually running inside the Electron client application and over RDP? 

If so, does the code work when you run it directly in nodejs on a machine that is located at the office? It should in my opinion not be running in a client anyway, for safety. After all there are passwords involved so you should keep this code safely in a central server that runs nodejs.

**Comment by ChristianHaase** [comment]
The activedirectory2 code is running inside the Electron app yes.

I am well aware that there is a security flaw in my Electron app. It is in the pipeline to change this. :)

**Comment by jurjendijkstra** [comment]
Ok so would it be possible to test the activedirectory part of the code (and config) in a nodejs script that is not using Electron but simply nodejs? like `node testactivedir.js`?

**Comment by ChristianHaase** [comment]
Yup, just tried it and everything works fine, but I've never had issues whilst developing. It's only an issue on the RD gateway, which makes sense since there might already be an active socket on 389, so that user will not be able to start another.

**Comment by jsumners** [comment]
There shouldn't be any reason to start listening locally on port `389`. Indeed, a typical user is not going to have permission to do that anyway. The reason for listening on port `389` would be to start an LDAP server for others to connect to. Your application should be establishing a connection to a _remote_ LDAP server on port `389`, which will pick a random port on the local system for communication. It looks like:

1. connect to `ldap://ldap.example.com:389`
2. remote server says "yep, welcome"
3. local app says "cool, I'm going to use port 12456 to talk to you"

It's a very basic TCP communication.
