### ISSUE TITLE
Environmental Variables. 

### ISSUE THREAD

**Issue by BrettMarshall16** [jsumners/node-activedirectory#96]
Not sure if its related to LDAP or this library but I am not able to use environmental variables with the config. Would be nice to be able to use .env files to substitute username and password. Currently get error:

`ERROR: {"lde_message":"80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580\u0000","lde_dn":null}`

**Comment by jsumners** [comment]
The configuration is supplied through the constructor. It's your app's responsibility to pass environment variables to libraries.
